
development:
  adapter: postgresql
  encoding: unicode
  database: big_data_development

test:
  adapter: postgresql
  encoding: unicode
  database: big_data_test

production:
  adapter: postgresql
  encoding: unicode
  database: big_data_production
